# tasks/main.yml
---
- name: Ensure puma config directory
  ansible.builtin.file:
    path: "{{ puma_config_dir }}"
    state: directory
    owner: "{{ puma_user }}"
    group: "{{ puma_user }}"
    mode: "0755"

- name: Ensure puma config file
  ansible.builtin.template:
    src: puma.rb.j2
    dest: "{{ puma_config_file }}"
    owner: "{{ puma_user }}"
    group: "{{ puma_user }}"
    mode: "0644"
